_target_: src.trainer.default.defaultTrainer
default_root_dir: ${work_dir}

min_epochs: 1
max_epochs: 100

accelerator: cpu
num_nodes: 0
strategy: auto
log_every_n_steps: 20
check_val_every_n_epoch: 1
profiler : null
