defaults:
  - regression: UNet
  - super_resolution: EDSR
  - _self_


instance:
  _target_: src.models.networks.end_2_end.end2EndNetwork
  regression_model: ${model.network.regression}
  super_resolution_model: ${model.network.super_resolution}