defaults:
  - network: End_2_end
  - loss: smooth_L1
  - metrics: classic_method
  - _self_

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

instance:
  _target_: src.models.module.Module
  network: ${model.network}
  loss: ${model.loss}
  train_metrics: ${model.metrics.train_metrics}
  val_metrics: ${model.metrics.val_metrics}
  test_metrics: ${model.metrics.test_metrics}
  optimizer: ${model.optimizer}
  scheduler: ${model.scheduler}
