# @package _global_

defaults:
  - default

aoi_name: test_opencanopy
project : "tree_predictions"
run_name:  EDSR_UNet_nMAE
run_version : v1

input_path :  ${data_dir}/sentinel/composites/one_month_image/
ckpt_path : /home/projects/ku_00196/people/thobou/tree/logs/tree/EDSR_UNet_nMAE/EDSR_UNet_nMAE_v3/best_checkpoints/epoch_005.ckpt

aoi_path: ${data_dir}/utils/geometries.geojson  # path to a shapefile (any file that can be read by geopandas.read_file), only used if aoi_bounds is null
split: test # select "test" tiles from "split" column (if aoi_path is not null)
lidar_year: null # select "tiles" from "lidar_year" column that match lidar_year (if aoi_path is not null)

