defaults:
    - default.yaml

upload_code_as_artifact:
    _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
    code_dir: ${work_dir}/src


log_image_predictions:
    _target_: src.callbacks.wandb_callbacks.LogImagePredictions
    num_samples: 8
    freq_train : null
