defaults:
    - default.yaml

upload_code_as_artifact:
    _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
    code_dir: ${work_dir}/src

watch_model:
    _target_: src.callbacks.wandb_callbacks.WatchModel
    log: "all"
    log_freq: 100

log_image_predictions:
    _target_: src.callbacks.wandb_callbacks.LogImagePredictions
    num_samples: 8
    freq_train : null
    min_value_normalization: 0
    max_value_normalization: 40
    mode : "height"
