defaults:
  - dataset: SR_composites_sentinel_dataset
  - _self_

instance:
  _target_: src.datamodules.datamodule.Datamodule
  patch_size_input: 64
  patch_size_target: 256
  batch_size: 16
  num_workers: 8
  persistent_workers: True
  max_n_inputs_for_moments_computation: 300
  max_n_inputs_per_epoch: null
  train_dataset: ${datamodule.dataset.train_dataset}
  val_dataset: ${datamodule.dataset.val_dataset}
  test_dataset: ${datamodule.dataset.test_dataset}
  normalization_save_path: ./
  normalization_constants: null

  