input_path: ./
target_path: ./
target_unit: dm
geometries_path: ./
replace_nan_by_zero_in_target: True
min_year: 2021
max_year: 2023
target_resolution: 2.5
input_resolution: 10
nb_timeseries_image: 8
duplication_level_noise : null

train_dataset:
  _target_: src.datamodules.datasets.timeseries_sentinel_dataset.sentinelDataset
  input_path: ${datamodule.dataset.input_path} 
  target_path: ${datamodule.dataset.target_path}
  target_unit: ${datamodule.dataset.target_unit} 
  geometries_path: ${datamodule.dataset.geometries_path} 
  replace_nan_by_zero_in_target: ${datamodule.dataset.replace_nan_by_zero_in_target} 
  min_year: ${datamodule.dataset.min_year} 
  max_year: ${datamodule.dataset.max_year} 
  target_resolution: ${datamodule.dataset.target_resolution}
  input_resolution: ${datamodule.dataset.input_resolution}  
  nb_timeseries_image: ${datamodule.dataset.nb_timeseries_image}
  duplication_level_noise: ${datamodule.dataset.duplication_level_noise}
  patch_size_input: ${datamodule.instance.patch_size_input}
  split: train

val_dataset:
  _target_: src.datamodules.datasets.timeseries_sentinel_dataset.sentinelDataset
  input_path: ${datamodule.dataset.input_path} 
  target_path: ${datamodule.dataset.target_path}
  target_unit: ${datamodule.dataset.target_unit} 
  geometries_path: ${datamodule.dataset.geometries_path} 
  replace_nan_by_zero_in_target: ${datamodule.dataset.replace_nan_by_zero_in_target} 
  min_year: ${datamodule.dataset.min_year} 
  max_year: ${datamodule.dataset.max_year} 
  target_resolution: ${datamodule.dataset.target_resolution}
  input_resolution: ${datamodule.dataset.input_resolution}  
  nb_timeseries_image: ${datamodule.dataset.nb_timeseries_image}
  duplication_level_noise: ${datamodule.dataset.duplication_level_noise}
  patch_size_input: ${datamodule.instance.patch_size_input}
  split: val

test_dataset:
  _target_: src.datamodules.datasets.timeseries_sentinel_dataset.sentinelDataset
  input_path: ${datamodule.dataset.input_path} 
  target_path: ${datamodule.dataset.target_path}
  target_unit: ${datamodule.dataset.target_unit} 
  geometries_path: ${datamodule.dataset.geometries_path} 
  replace_nan_by_zero_in_target: ${datamodule.dataset.replace_nan_by_zero_in_target} 
  min_year: ${datamodule.dataset.min_year} 
  max_year: ${datamodule.dataset.max_year} 
  target_resolution: ${datamodule.dataset.target_resolution}
  input_resolution: ${datamodule.dataset.input_resolution}  
  nb_timeseries_image: ${datamodule.dataset.nb_timeseries_image}
  duplication_level_noise: ${datamodule.dataset.duplication_level_noise}
  patch_size_input: ${datamodule.instance.patch_size_input}
  split: test