tree_cover_threshold: 2
forest_mask_path : ./
classification_path : ./
classes_to_keep : [5]


train_metrics: null

val_metrics:
  _target_: src.models.metrics.metrics.OpenCanopyMetrics
  tree_cover_threshold: ${model.metrics.tree_cover_threshold}
  forest_mask_path : ${model.metrics.forest_mask_path}
  classification_path : ${model.metrics.classification_path}
  classes_to_keep : ${model.metrics.classes_to_keep}
  target_patch_size : ${datamodule.instance.patch_size_target}

test_metrics:
  _target_: src.models.metrics.metrics.OpenCanopyMetrics
  tree_cover_threshold: ${model.metrics.tree_cover_threshold}
  forest_mask_path : ${model.metrics.forest_mask_path}
  classification_path : ${model.metrics.classification_path}
  classes_to_keep : ${model.metrics.classes_to_keep}
  target_patch_size : ${datamodule.instance.patch_size_target}
